### ISSUE TITLE
Documentation issue on how-to-use.rst

### ISSUE THREAD

**Issue by amartens1** [sthima/libstapsdt#27]
There is a copy/paste issue on the documentation, [file how-to-use.rst](https://github.com/sthima/libstapsdt/blob/master/docs/how-it-works/how-to-use.rst)

The loop on the example (first code block) tries to fire a probe from an unknown array (`probeFire(probes[idx], i++, j--);`)

It says
```c
  while(i) {
    printf("Firing probe...\n");
    if(probeIsEnabled(probe)) {
      probeFire(probes[idx], i++, j--);
      printf("Probe fired!\n");
      i = 0;
    }
    sleep(1);
  }
```

It should rather say
```c
while(i) {
  printf("Firing probe...\n");
  if(probeIsEnabled(probe)) {
    probeFire(probe, "I'm a runner!");
    printf("Probe fired!\n");
    i = 0;
  }
  sleep(1);
}
```
Hope this helps

**Comment by mmarchini** [comment]
Thank you!
